---
pagetitle: "Task clase 7"
output: html_document
---
<!-- Estilo del HTML -->
<style type="text/css">
h1 {font-size: 32px;color: #00008B}
h1.title {font-size: 32px;}
h2 {font-size: 30px;color: #4169E1}
h3 {font-size: 26px;color: #4169E1}
h4 {font-size: 24px;}
 p {font-size: 22px; color: black}
li { font-size: 18px;color: black}
.table th:not([align]) {text-align: left;}
</style>

<!-- Configuración de la consola de R -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T , eval = T , warning = T)
```


# 1. Loops importando archivos

* Van a usar el paquete 'tidyverse' y 'readxl' (depronto se me escapa otro)

* Descargue los archivos de el siguiente link: [clic aquí](https://www.dropbox.com/sh/o6edda8hmfooate/AACYr4N1wkwL9IMVTgUHAJpya?dl=0)

este link contiene las bases de datos con los registros oficiales de los delitos
reportados en Colombia entre 2010-2019 y fueron tomados de: [link a GICRI](https://www.policia.gov.co/grupo-información-criminalidad/estadistica-delictiva)

* Usando las funciones list.files() y algunas de las 'string functions' vistas en clases anteriores intente cargar por medio de un loop todas las bases de datos (sugiero alojar cada base de datos dentro de una posición de un objeto tipo lista). Limpie los nombres de las variables

* Después intente agruparlas en 3 dataframes por tipo de delito: homicidios, h_personas y h_motos. 

* Exporte los 3 objetos que contienen los dataframe. Hágalo en formato .rds.

# 2. Loops anidados

* Intente hacer un loop anidado (2 niveles) en el que pinte sobre la consola las vocales.




